### ISSUE TITLE
Remove errorprone due to performance overhead

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#3573]
I have just tried running `./gradlew clean classes` on my developer laptop. It takes around 2 minutes. When I try to disable `otel.errorprone-conventions` from `otel.java-conventions` this time got down to around 1m 10s.

Our recent [build scans from CI](https://scans.gradle.com/s/4jrdtpmgwg3ls/performance/execution) show too much `javaCompile` tasks as top contributors to build time. It is totally not acceptable that compiling java sources takes more time than actually running integration tests with the agent.

There is known unresolved performance overhead of the errorProne: https://github.com/google/error-prone/issues/994

Not performance related but, I just discovered that error prone is an actual compiler which replaces javac. Not sure I actually trust it to produce our final binary artitfacts.

**Comment by anuraaga** [comment]
Let's not be too hasty here.

The replacement of javac is only needed for Java 9 and hasn't been done for a while now, it's a javac plugin. The issue seems to mostly be about the previous javac replacement approach and mentions some classpath caching issues are solved with the plugin (now-only) approach. While there's something to say about a plugin being able to do whatever it wants, we'd give up nullaway and/or checker framework too if we're really concerned. Having these checks is probably more likely to produce "better bytecode" though.

I think the build scan is showing individual tasks taking 100x time, not just double, and I guess you did find the cause for it. 2x compile time doesn't seem unacceptable.

I didn't check empirically, but anecdotally errorprone felt faster than the spotbugs tasks running. Or we can just remove all checks of course and have a 5 minute build :P

**Comment by anuraaga** [comment]
By the way, I never considered the performance implication of each check so only disable ones that we find to cause us problems. There are probably ones that don't provide any real value for us and can try disabling them. Don't expect it to be a night and day change but can optimize a bit if we want to. Again, I don't think 2x is something to get too worried about though.

**Comment by trask** [comment]
I like the improvements that errorprone brought to the codebase (#3155), and I like not needing to think about many of those details when reviewing PRs. I'm hoping we can solve perf (and [usability](#3579)) issues without removing errorprone.

**Comment by trask** [comment]
@iNikem is this still an issue?

**Comment by iNikem** [comment]
> @iNikem is this still an issue?

I still see unexpectedly long compilation times, e.g. in https://scans.gradle.com/s/jgowxabuj3uhi/performance/execution. At least worth investigation.

**Comment by anuraaga** [comment]
@iNikem The linked build downloads 2GiB of dependencies spending 1h57m. Should we create a new issue to investigate build cache misses like that one?

**Comment by iNikem** [comment]
The linked build is from "nightly without cache". I assume it does not use cache by design?

**Comment by anuraaga** [comment]
@iNikem Ah - that explains the slowness then right? Gradle's dependency download time gets attributed to compilation tasks as we found.

**Comment by iNikem** [comment]
You are correct :) Ok, can close for now.
