### ISSUE TITLE
@WithSpan not working with Springboot

### ISSUE THREAD

**Issue by axiangcoding** [open-telemetry/opentelemetry-java-instrumentation#6513]
**Describe the bug**
Following the documentation's instructions: https://opentelemetry.io/docs/instrumentation/java/automatic/annotations/, I set up javaagent and was able to get span successfully, but when I use @WithSpan, no span is created

**Steps to reproduce**
- Init a very simple springboot 2.7.3 application 
`dependencies in pom.xml`:
```
<dependencies>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
    </dependency>

    <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <optional>true</optional>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-test</artifactId>
        <scope>test</scope>
    </dependency>
    ...
    
    <dependency>
        <groupId>io.opentelemetry.instrumentation</groupId>
        <artifactId>opentelemetry-instrumentation-annotations</artifactId>
        <version>1.17.0-alpha</version>
    </dependency>
</dependencies>
```
 `DemoController.java`:
```
package com.example.demo.controller;

import com.example.demo.entity.GeneralResult;
import com.example.demo.service.DemoService;
import org.springframework.web.bind.annotation.*;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import java.util.HashMap;
import java.util.Map;

@RestController
@RequestMapping("demo")
public class DemoController {
    @Resource
    DemoService demoService;

    @GetMapping("/get")
    public GeneralResult getDemo() {
        Map<String, Object> map = new HashMap<>();
        map.put("randomInt", demoService.randomInt(System.currentTimeMillis()));
        return GeneralResult.success(map);
    }
}
```
`DemoService`:
```
package com.example.demo.service;

import io.opentelemetry.instrumentation.annotations.SpanAttribute;
import io.opentelemetry.instrumentation.annotations.WithSpan;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.Random;

@Service
@Slf4j
public class DemoService {
    @WithSpan
    public Integer randomInt(@SpanAttribute long seed) {
        return new Random(seed).nextInt();
    }
}
```

- Config Environment and javaagent in Intellj Idea
```
env: OTEL_METRICS_EXPORTER=none;OTEL_SERVICE_NAME=java-demo;OTEL_TRACES_EXPORTER=otlp
vm options: -javaagent:lib/opentelemetry-javaagent.jar
```
- Start the application and then request the `demo/get`, and successfully collect two spans, named `/demo/get` and `DemoController.getDemo`, but missing the expected `DemoService.randomInt`

**What did you expect to see?**
successfully collect  `/demo/get` , `DemoController.getDemo` and `DemoService.randomInt` and any method with @WithSpan

**What did you see instead?**
@WithSpan not working propertly, missing the expected span `DemoService.randomInt`

**What version are you using?**
```
<dependency>
    <groupId>io.opentelemetry.instrumentation</groupId>
    <artifactId>opentelemetry-instrumentation-annotations</artifactId>
    <version>1.17.0-alpha</version>
</dependency>
```

**Environment**
Compiler: Eclipse Adoptium\jdk-8.0.342.7-hotspot
OS: Windows10

**Comment by trask** [comment]
hi @axiangcoding! can you post a small repro of the issue? it should be working (and the tests for this are passing), so it may be something less obvious that we have overlooked, thx!

**Comment by axiangcoding** [comment]
> hi @axiangcoding! can you post a small repro of the issue? it should be working (and the tests for this are passing), so it may be something less obvious that we have overlooked, thx!

hi, @trask ! thanks for the answer so quickly. please visit https://github.com/axiangcoding/withspan-error-with-springboot for full example.

btw, i'm using jaeger as collector. docker-compose.yml as followed:
```
version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.37
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
  
```

**Comment by trask** [comment]
hi @axiangcoding, I tried it out using

```
java -javaagent:opentelemetry-javaagent.jar -Dotel.traces.exporter=logging -Dotel.metrics.exporter=none -jar target/demo-0.0.1-SNAPSHOT.jar
```

and was able to see the `DemoService.randomInt` span:

> [otel.javaagent 2022-08-25 20:27:34:408 -0700] [http-nio-8080-exec-1] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - '**DemoService.randomInt**' : 64ad1f60d3dfdddb5b4b2cf25ac7f4e8 876828bb98eb6d6d INTERNAL [tracer: io.opentelemetry.opentelemetry-instrumentation-annotations-1.16:1.17.0-alpha] AttributesMap{data={thread.name=http-nio-8080-exec-1, seed=1661484454397, code.function=randomInt, thread.id=135, code.namespace=com.example.demo.service.DemoService}, capacity=128, totalAddedValues=5}
[otel.javaagent 2022-08-25 20:27:34:476 -0700] [http-nio-8080-exec-1] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - '**DemoController.getDemo**' : 64ad1f60d3dfdddb5b4b2cf25ac7f4e8 5eb6b3fb6b4cb7e6 INTERNAL [tracer: io.opentelemetry.spring-webmvc-3.1:1.17.0-alpha] AttributesMap{data={thread.name=http-nio-8080-exec-1, thread.id=135}, capacity=128, totalAddedValues=2}
[otel.javaagent 2022-08-25 20:27:34:484 -0700] [http-nio-8080-exec-1] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - '**/demo/get**' : 64ad1f60d3dfdddb5b4b2cf25ac7f4e8 b66ad5c693b46789 SERVER [tracer: io.opentelemetry.tomcat-7.0:1.17.0-alpha] AttributesMap{data={http.method=GET, http.scheme=http, http.status_code=200, http.user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.63, http.route=/demo/get, thread.id=135, net.sock.peer.port=64804, thread.name=http-nio-8080-exec-1, http.host=localhost:8080, http.target=/demo/get, net.sock.peer.addr=0:0:0:0:0:0:0:1, http.flavor=1.1, net.transport=ip_tcp}, capacity=128, totalAddedValues=13}

**Comment by axiangcoding** [comment]
@trask i try the same command in Windows10, still not see **DemoService.randomInt**
```
PS D:\Projects\demo> java "-javaagent:opentelemetry-javaagent.jar" "-Dotel.traces.exporter=logging" "-Dotel.metrics.exporter=none" -jar target/demo-0.0.1-SNAPSHOT.jar      
[otel.javaagent 2022-08-26 11:36:59:848 +0800] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.12.0

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.3)

2022-08-26 11:37:03.718  INFO 16864 --- [           main] com.example.demo.DemoApplication         : Starting DemoApplication v0.0.1-SNAPSHOT using Java 1.8.0_342 on CN-FZ-WYX with PID 16864 (D:\Projects\demo\target\demo-0.0.1-SNAPS
HOT.jar started by yuxiang_wu in D:\Projects\demo)
2022-08-26 11:37:03.740  INFO 16864 --- [           main] com.example.demo.DemoApplication         : No active profile set, falling back to 1 default profile: "default"
2022-08-26 11:37:05.759  INFO 16864 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-08-26 11:37:05.870  INFO 16864 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-08-26 11:37:05.871  INFO 16864 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.65]
2022-08-26 11:37:06.029  INFO 16864 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-08-26 11:37:06.029  INFO 16864 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2231 ms
2022-08-26 11:37:06.795  INFO 16864 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2022-08-26 11:37:08.181  INFO 16864 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2022-08-26 11:37:08.204  INFO 16864 --- [           main] com.example.demo.DemoApplication         : Started DemoApplication in 5.142 seconds (JVM running for 8.642)
2022-08-26 11:37:10.324  INFO 16864 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-08-26 11:37:10.325  INFO 16864 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-08-26 11:37:10.327  INFO 16864 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
[otel.javaagent 2022-08-26 11:37:10:465 +0800] [http-nio-8080-exec-1] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - 'DemoController.getDemo' : 5d24d3dab07d1bfc2034e33779495960 e905fdc6b7d22f94 INTERNAL [tracer: io.ope
ntelemetry.spring-webmvc-3.1:1.12.0] AttributesMap{data={thread.id=103, thread.name=http-nio-8080-exec-1}, capacity=128, totalAddedValues=2}
[otel.javaagent 2022-08-26 11:37:10:473 +0800] [http-nio-8080-exec-1] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - '/demo/get' : 5d24d3dab07d1bfc2034e33779495960 2b962475bdd4330a SERVER [tracer: io.opentelemetry.tomc
at-7.0:1.12.0] AttributesMap{data={http.user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36, http.route=/demo/get, http.status_code=200, thread.id=103, http.sche
me=http, http.method=GET, net.peer.port=55397, net.transport=ip_tcp, http.flavor=1.1, http.target=/demo/get, http.host=localhost:8080, net.peer.ip=0:0:0:0:0:0:0:1, thread.name=http-nio-8080-exec-1}, capacity=128, totalAddedValues=13
}

```

Maybe there is some problems under Windows10? i will try running application under Linux later, will feeback soon

**Comment by trask** [comment]
@axiangcoding that is odd, I'm on Windows 10 too, can you try mvn clean package to make sure you're not running older code before you added the annotation?

**Comment by mateuszrzeszutek** [comment]
Hey @axiangcoding ,
It looks like you're using a pretty old version of the javaagent:
```
...VersionLogger - opentelemetry-javaagent - version: 1.12.0
```
Can you try using 1.17?

**Comment by axiangcoding** [comment]
@trask version 1.17 works!
 I downloaded the jar package directly from the hyperlink in the documentation (https://opentelemetry.io/docs/instrumentation/java/automatic/) and didn't notice that the jar package was outdated.
thanks again.

**Comment by mateuszrzeszutek** [comment]
Ouch, looks like we missed that one link. Thanks for pointing that out! I'll update it to the latest version.
